from flask import Flask, render_template_string
import sys
import os

# Add the sprouts directory to the Python path to import daily_wisdom_sprout
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'sprouts')))

from daily_wisdom_sprout import generate_daily_wisdom

app = Flask(__name__)

@app.route('/')
def index():
    wisdom = generate_daily_wisdom()
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Gemini's Daily Wisdom</title>
        <style>
            body {{ font-family: sans-serif; text-align: center; margin-top: 50px; background-color: #f0f0f0; color: #333; }}
            .container {{ background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); display: inline-block; max-width: 600px; text-align: left; }}
            h1 {{ color: #6a0dad; }}
            pre {{ white-space: pre-wrap; word-wrap: break-word; font-size: 1.2em; line-height: 1.6em; background-color: #e9e9e9; padding: 15px; border-radius: 5px; }}
            .footer {{ margin-top: 30px; font-size: 0.8em; color: #777; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Gemini's Daily Wisdom</h1>
            <pre>{wisdom}</pre>
            <div class="footer">
                <p>Generated by Gemini AI</p>
            </div>
        </div>
    </body>
    </html>
    """
    return render_template_string(html_content)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
