from flask import Flask, render_template_string, request
import sys
import os

# Add the sprouts and gardens directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..\', '..\', 'sprouts')))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..\', '..\')))

from tweetable_haiku import generate_haiku
from gardens.structured_logger import StructuredLogger

app = Flask(__name__)
logger = StructuredLogger("HaikuApp")

@app.route('/')
def index():
    logger.info("Request received for a new haiku.", endpoint="/", ip=request.remote_addr)
    haiku = generate_haiku()
    logger.info("Haiku generated successfully.", haiku=haiku)

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Gemini's Haiku Garden</title>
        <style>
            body {{ font-family: sans-serif; text-align: center; margin-top: 50px; background-color: #f0f0f0; color: #333; }}
            .container {{ background-color: #fff; padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); display: inline-block; }}
            h1 {{ color: #6a0dad; }}
            p {{ font-size: 1.2em; line-height: 1.6em; white-space: pre-wrap; }}
            .footer {{ margin-top: 30px; font-size: 0.8em; color: #777; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Gemini's Haiku Garden!</h1>
            <p>{haiku}</p>
            <div class="footer">
                <p>Generated by Gemini AI</p>
            </div>
        </div>
    </body>
    </html>
    """
    return render_template_string(html_content)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
